// Generated by tools/loadgen/loadgen.mjs --emit-k6 from loadtests/smoke.config.json.
// Do not edit by hand: edit the config, regenerate, and the Node runner and
// k6 keep describing the same experiment (same tenants, mixes, pacing, gates).
//
//   k6 run loadtests/smoke.js                     # against a local API
//   BASE_URL=https://staging.example.com k6 run loadtests/load.js
import http from 'k6/http';
import { check, sleep } from 'k6';
import exec from 'k6/execution';
import { Counter } from 'k6/metrics';

const errors5xx = new Counter('errors_5xx');
const throttled429 = new Counter('throttled_429');

const BASE = __ENV.BASE_URL || "http://127.0.0.1:3000";
const SEED_PASSWORD = __ENV.SEED_PASSWORD || "Seed-Passw0rd-2026!";
const VICTIM_PLANS = new Set(["free"]);
const THINK_MS = 0;
const SEED_PROJECTS = 3;
const TENANT_SPECS = [{"plan":"free"}];
const SCENARIOS_BY_PLAN = {
  "free": [
    {
      "name": "me",
      "method": "GET",
      "path": "/v1/me",
      "weight": 1,
      "thinkMs": 20
    },
    {
      "name": "list-projects",
      "method": "GET",
      "path": "/v1/projects?limit=25",
      "weight": 4,
      "thinkMs": 20
    },
    {
      "name": "get-project",
      "method": "GET",
      "path": "/v1/projects/{project}",
      "weight": 3,
      "thinkMs": 20
    },
    {
      "name": "create-project",
      "method": "POST",
      "path": "/v1/projects",
      "weight": 1,
      "idempotency": true,
      "body": {
        "name": "smoke write"
      },
      "thinkMs": 50
    },
    {
      "name": "enqueue-report",
      "method": "POST",
      "path": "/v1/projects/{project}/reports",
      "weight": 1,
      "idempotency": true,
      "body": {
        "format": "csv"
      },
      "thinkMs": 100
    },
    {
      "name": "plans-public",
      "method": "GET",
      "path": "/v1/plans",
      "weight": 1,
      "thinkMs": 20
    }
  ]
};

export const options = {
  vus: 4,
  duration: "6s",
  thresholds: {
  'errors_5xx': ['count==0'],
  'http_req_duration': ['p(99)<1500'],
  },
};

// NOT TRANSLATABLE to k6: totals.requests >= 20 (server-side metric; use the Node loadgen or Prometheus).

export function setup() {
  // Same provisioning the Node runner does: one workspace per spec (or a
  // seeded login), then enough projects that reads hit real pages + a warm cache.
  const runTag = Date.now().toString(36);
  const tenants = [];
  TENANT_SPECS.forEach((spec, i) => {
    let t;
    if (spec.useSeed) {
      const email = `owner@${spec.useSeed}.test`;
      const res = postWithRetry("/v1/auth/login", { email, password: SEED_PASSWORD, tenantSlug: spec.useSeed });
      if (res.status !== 200) throw new Error(`seed login failed for ${email}: ${res.status}`);
      const body = res.json();
      t = { slug: spec.useSeed, plan: "pro", token: body.accessToken, projects: [], jobs: [] };
    } else {
      const slug = `load-${runTag}${i}`;
      const password = spec.password || "Load-Test-Passw0rd-2026!";
      const res = postWithRetry("/v1/auth/register", {
        tenant: { name: `Load ${slug}`, slug, plan: spec.plan },
        user: { email: `owner@${slug}.test`, password, displayName: "Load Runner" },
      });
      if (res.status !== 201) throw new Error(`register failed: ${res.status} ${res.body}`);
      const body = res.json();
      t = { slug, plan: spec.plan, token: body.accessToken, projects: [], jobs: [] };
    }
    for (let p = 0; p < SEED_PROJECTS; p++) {
      const res = http.post(`${BASE}/v1/projects`, JSON.stringify({ name: `Load project ${p}`, tags: ["load"] }), {
        headers: authHeaders(t, `seed-${t.slug}-${p}`),
      });
      if (res.status === 201) t.projects.push(res.json("id"));
      else if (res.status === 402) break; // plan quota is a measured property, not something to bypass
      else if (res.status >= 500) throw new Error(`seed failed: ${res.status}`);
    }
    t.role = VICTIM_PLANS.has(t.plan) ? "victim" : "load";
    tenants.push(t);
  });
  return { tenants };
}

export default function (data) {
  const tenant = data.tenants[(exec.vu.idInTest - 1) % data.tenants.length];
  const list = SCENARIOS_BY_PLAN[tenant.plan] || SCENARIOS_BY_PLAN.free || [];
  if (!list.length) throw new Error(`no scenarios for plan ${tenant.plan}`);
  const s = pickWeighted(list);
  const path = expand(s.path, tenant);
  const headers = authHeaders(tenant, s.idempotency ? `load-${exec.vu.idInTest}-${exec.scenario.iterationInTest}` : null);
  Object.assign(headers, s.headers || {});
  const res = http.request(s.method || "GET", BASE + path, s.body ? JSON.stringify(deepExpand(s.body, tenant)) : null, {
    headers,
    // `name` is what k6 groups URLs by: the route template, never the expanded uuid.
    tags: { name: `${s.method || "GET"} ${s.path}`, scenario: s.name, tenant: tenant.slug, plan: tenant.plan, role: tenant.role },
  });
  if (res.status >= 500) errors5xx.add(1, { role: tenant.role });
  if (res.status === 429) throttled429.add(1, { plan: tenant.plan, role: tenant.role });
  if (res.status === 202) {
    const jobId = res.json("jobId");
    if (jobId) tenant.jobs.push(jobId); // later {job} polls use real ids
  }
  check(res, { "not 5xx": (r) => r.status < 500 });
  const pace = s.thinkMs ?? THINK_MS;
  if (pace) sleep((pace / 1000) * (0.8 + Math.random() * 0.4));
}

function authHeaders(tenant, idempotencyKey) {
  const h = { "content-type": "application/json", authorization: `Bearer ${tenant.token}`, "x-load-vu": "k6" };
  if (idempotencyKey) h["idempotency-key"] = idempotencyKey;
  return h;
}

function postWithRetry(path, body) {
  // Setup shares the per-IP auth bucket with every other VU provisioning at
  // the same moment; a 429 here is the brake working, so honour it.
  for (let attempt = 0; attempt < 6; attempt++) {
    const res = http.post(BASE + path, JSON.stringify(body), { headers: { "content-type": "application/json" } });
    if (res.status !== 429) return res;
    sleep(Number(res.headers["Retry-After"] || 1) + 0.1);
  }
  throw new Error(`setup still throttled on ${path}`);
}

function pickWeighted(list) {
  const total = list.reduce((a, s) => a + (s.weight ?? 1), 0);
  let r = Math.random() * total;
  for (const s of list) {
    r -= s.weight ?? 1;
    if (r <= 0) return s;
  }
  return list[list.length - 1];
}

function expand(template, tenant) {
  const pick = (list) => (list.length ? String(list[Math.floor(Math.random() * list.length)]) : null);
  return template
    .replace(/{slug}/g, tenant.slug)
    .replace(/{project}/g, () => pick(tenant.projects) || "00000000-0000-0000-0000-000000000000")
    .replace(/{job}/g, () => pick(tenant.jobs) || pick(tenant.projects) || "00000000-0000-0000-0000-000000000000");
}

function deepExpand(value, tenant) {
  if (typeof value === "string") return expand(value, tenant);
  if (Array.isArray(value)) return value.map((v) => deepExpand(v, tenant));
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, deepExpand(v, tenant)]));
  }
  return value;
}
