import { describe, expect, it } from 'vitest';
import { LABELS, METRICS, METRIC_OWNERSHIP } from '../src/metrics.js';

/**
 * The metric-name registry is the contract between three things that live in different
 * places and cannot see each other: the code that observes, the alert rules in
 * `infra/prometheus/alerts.yml`, and the Grafana queries generated by
 * `infra/grafana/dashboards/build.mjs`.
 *
 * A name in this table with nothing registering it is not a cosmetic problem. The
 * dashboard panel renders, Prometheus answers `vector(0)` for the missing series, and
 * every reader concludes "no errors, no throttling, no traffic from that tenant" —
 * which is the shape of a silent monitoring outage. So: no dangling names, no
 * unowned names, and no metric whose name is spelled two different ways.
 */
const NAMES = Object.values(METRICS) as string[];

describe('metric name registry', () => {
  it('has no duplicate names behind different keys', () => {
    expect(new Set(NAMES).size).toBe(NAMES.length);
  });

  it('uses Prometheus naming conventions', () => {
    for (const [key, name] of Object.entries(METRICS)) {
      expect(name, key).toMatch(/^[a-z][a-z0-9_]*$/);
      // Counters/gauges ending in a unit are fine; anything that can only ever
      // increase must carry `_total`, or PromQL's rate()/increase() helpers and
      // `promtool` linting start disagreeing with the code.
      if (
        /(requests|errors|events|decisions|lookups|queries|ticks|letters|sent|keys|scrapes|published)$/.test(
          name,
        )
      ) {
        expect(name, `${key} must end in _total`).toMatch(/_total$/);
      }
    }
  });

  it('assigns exactly one owner set per name, with no gap and no leftover', () => {
    // Keyed by the METRICS key, so `Record<MetricName, …>` already refuses a missing or
    // misspelled entry at compile time. Asserted at runtime as well because the type is
    // `Record<keyof typeof METRICS>` and a *new* metric added to the object literal is
    // exactly the case a reviewer must not have to think about.
    const keys = Object.keys(METRICS);
    const owned = Object.keys(METRIC_OWNERSHIP);
    expect([...owned].sort()).toEqual([...keys].sort());
    for (const [key, owners] of Object.entries(METRIC_OWNERSHIP)) {
      expect(owners.length, key).toBeGreaterThan(0);
      expect(new Set(owners).size, `${key} repeats an owner`).toBe(owners.length);
      for (const owner of owners) {
        expect(['api', 'worker'], `${key}.${owner}`).toContain(owner);
      }
    }
  });

  it('keeps the names that were rejected as unmeasurable out of the registry', () => {
    // Each of these was considered and dropped (the reasons are in the comment in
    // src/metrics.ts). Asserting their absence is what stops someone from "fixing"
    // the missing metric by adding the constant back without an implementation.
    for (const dead of [
      'ratelimit_bucket_utilization',
      'redis_commands_total',
      'queue_failed_total',
      'tenant_rejected_requests_total',
    ]) {
      expect(NAMES, dead).not.toContain(dead);
    }
  });

  it('labels with single-token names that do not collide with reserved prefixes', () => {
    const values = Object.values(LABELS) as string[];
    expect(new Set(values).size).toBe(values.length);
    for (const label of values) {
      expect(label).toMatch(/^[a-z][a-zA-Z0-9_]*$/);
      expect(label.startsWith('__'), label).toBe(false);
    }
    // `tenant` is deliberately the slug, not the id: a graph axis a human can read,
    // and bounded by the top-N allow-list rather than by how many workspaces exist.
    expect(LABELS.tenant).toBe('tenant');
    expect(LABELS.routeClass).toBe('route_class');
  });
});
